[pytest]
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning

[coverage:run]
omit =
    backend/logger.py
    backend/database/migrations/*

[coverage:report]
fail_under = 83
show_missing = true
